seed: 42

train:
  epochs: 50
  accelerator: "gpu"
  devices: [2,3]
  strategy: "DDP"
  precision: 16
  checkpoint_dir: "tmp/checkpoint"
  optimizer:
    NAME: "adam"
    learning_rate: 0.0005
    weight_decay: 0.0
    momentum: 0.9
  scheduler:
    NAME: "stepLR"
    step_size: 10
    gamma: 0.5

model:
  architecture: 'unetplusplus-with-aspp-fpn' #'FPN' 
  backbone: 'efficientnet-b6'
  atrous_rates: [6, 12, 18]
  segmentation_channels: 32
  classes: 1

data:
  batch_size: 8
  accumulate_grad_batches: 2
  num_workers: 16
  n_split: 4
  spatial_size: 512

logger:
  wandb:
    use: True
    project: 'hubmap-organ-segmentation'
